---
title: "Percolation Analysis – Building a Package"
author:
  -Maddison, Simon
  
  -Schmidt, Sophie C.

date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
    bookdown::word_document2:
      fig_caption: yes
csl: RGK_archaeology_DGUF.csl
bibliography: sitedefinition.bib
abstract: |
  The aim here is to create functions for percolation in R.
keywords: |
  spatial analysis; percolation; clustering algorithm
---

```{r, setup, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  cache = TRUE,
  comment = "#>",
  fig.path = "../figures/"
)


library(percopackage) # Or use devtools::load_all('.', quiet = T) if your code is in script files, rather than as functions in the `/R` diretory
```

# Data is in source_data

Bsp Datensatz hier sei sNL

```{r include=FALSE}

# create df from input data set
data <- read.csv("raw_data/BefundesNL-minimal.csv", sep = ",") #' crazy mistakes happen if this is wrong...
#' This file needs three columns: PlcIndex, Easting, Northing in this order.
#' Additional fields Lat Long not used for this program.
#' Note that the Easting and Northing need to be UK grid references with the Alphabetic
#'  grid square converted to a numeric prefix for each
#' List any entries with null values and write to file


library(maptools)
library(rgdal)
library(stringr)
library(igraph)
sNL_shape <- readOGR(dsn="shape_files/alle_Schnitt-Fundstellen.shp")


percolate_alles(data = data, radius_values = 10, limit = 500, radius_unit = 1, upper_radius = 200, lower_radius = 20, step_value = 20)

source("R/nodes_clust.R")
percolate2(data = data, radius_values = 10, limit = 500, radius_unit = 1, upper_radius = 200, lower_radius = 20, step_value = 20)

source("R/map_clust.R")
mapClusters(data = data, radius_values = 10, limit = 500, radius_unit = 1, upper_radius = 200, lower_radius = 20, step_value = 20, shape = sNL_shape, map_name = "sNL-Karte")


library(calibrate)
library(Hmisc)

source("R/cluster_frequency_script.v2.17.R")
clusterFrequency(radius_unit = 1, upper_radius = 200, lower_radius = 20, step_value = 20)


```




# Acknowledgements

<!-- The following line inserts a page break when the output is MS Word. For page breaks in PDF, use \newpage on its own line.  -->
##### pagebreak

# References 
<!-- The following line ensures the references appear here for the MS Word or HTML output files, rather than right at the end of the document (this will not work for PDF files):  -->
<div id="refs"></div>

##### pagebreak

### Colophon

This report was generated on `r Sys.time()` using the following computational environment and dependencies: 

```{r colophon, cache = FALSE}
# which R packages and versions?
devtools::session_info()
```

