
#' based on CLUSTER FREQENCY PLOTTING SCRIPTv2.17 by Simon Maddison, 10th May 2015
#' This script extracts cluster frequency data and plots it for a range of percolation radii
#' The data is in the analysis_results-directory in text files created by the nodes_clust_freq-function;
#' 	each file is a list of Place indices, with the identity of each cluster
#' 	which it is a member of.
#' 	radius-values have been stored in the working_data-directory.
#' 	output will be put into /analysis_results
#' @author Simon Maddison
#' @author Sophie C. Schmidt
#' 
#' @import stats
#' @import calibrate
#' @import Hmisc
#' @import grDevices
#' @import graphics
#' @import utils
#' @param source_file_name needs input of source file name for plotting
#' @return plotClustFreq 3 plots of radius to maximum cluster size, radius to mean cluster size and radius to normalized max. cluster size
#' 
#' @export plotClustFreq
#'
## SM: problem with the mean and normalized values being stored as factors. Resolved.



# paths definition
plotClustFreq <- function(source_file_name = source_file_name) {
 
  path_working <- paste(file.path(getwd(),"working_data"))
  path_results <- paste(file.path(getwd(),"analysis_results"))

# load data generated by nodes_clust_freq-function
file_name <- paste(file.path(path_results,"analysis_by_radius.csv"))
analysis_by_radius <- read.csv2(file_name,sep=",")

# load source_file_name if put out by mapClusters, if it was saved there. otherwise use input


if ( file.exists(file.path(path_working, "source_file_name_out.csv"))) {
source_file_name <- read.csv(file.path(path_working, "source_file_name_out.csv"), sep = " ")
source_file_name <- source_file_name[1,1] 
} else if ( exists("source_file_name")) {
  source_file_name <- source_file_name
  print(paste("source_file_name is", source_file_name))
} else {
  print("source_file_name input needed")
}


# Read in distance thresholds - this ensures same values used as in clustering script, where it was saved
file_name <- paste(file.path(path_working, "working_data.csv"))
radius_values <- read.csv2(file_name,header=TRUE, sep = ",")
upper_radius <- radius_values$upper_radius
lower_radius <- radius_values$lower_radius
step_value <- radius_values$step_value
radius_unit <- radius_values$radius_unit
	
if (radius_unit == 1)
{unit_text <- "m"
} else if (radius_unit == 1000)
{unit_text <- "km"
} else {
  unit_text <- paste(radius_unit, "m", sep="")}	
	
	# output as png files

#removed if-condition  about percolation

# Plot radius vs max_clust_size

  output_file <- paste(file.path(path_results,"radius_to_max_cluster_size.png"))
	png(file=output_file, units="cm", width=21, height=21, res=300)
	
	plot(analysis_by_radius$radius,analysis_by_radius$max_clust_size,
	     main=paste("Max cluster size vs radius "),
	     sub=paste("Source File: ",source_file_name),
	     xlab=paste("radius ", unit_text),
	     ylab="max cluster size", type="b")
#	textxy(analysis_by_radius$radius,analysis_by_radius$max_clust_size,analysis_by_radius$radius, col="red", cex=.8)
	# at the moment some weird mistake here: Error in if (sum(posXposY) > 0) text(X[posXposY], Y[posXposY], labs[posXposY],  : 
#	missing value where TRUE/FALSE needed
	# there shouldn't be any values missing.
	dev.off()	
	# Plot radius vs mean_clust_size
	
	output_file <- paste(file.path(path_results,"radius_to_mean_cluster_size.png"))
	png(file=output_file, units="cm", width=21, height=21, res=300)
	#SM: convert factor to numeric
	mean_clust_size_values <- as.numeric(as.character(analysis_by_radius$mean_clust_size))
	plot(analysis_by_radius$radius,mean_clust_size_values ,
	     main=paste("Mean cluster size vs radius "),
	     sub=paste("Source File: ",source_file_name),
	     xlab=paste("radius ", unit_text),
	     ylab="mean cluster size", type="b")
#	textxy(analysis_by_radius$radius,analysis_by_radius$mean_clust_size,analysis_by_radius$radius, col="red", cex=.8)
	
	dev.off()
	# Plot radius vs normalized max_clust_size
	
	output_file <- paste(file.path(path_results,"radius_to_norm_max_cluster_size.png"))
	png(file=output_file, units="cm", width=21, height=21, res=300)
	#SM: convert factor to numeric
	max_normalized_values <- as.numeric(as.character(analysis_by_radius$max_normalized))
	plot(analysis_by_radius$radius,max_normalized_values,
	     main=paste("Max cluster size (normalized) vs radius "),
	     sub=paste("Source File: ",source_file_name),
	     xlab=paste("radius ", unit_text),
	     ylab="max cluster size (normalized)", type="b")
#	textxy(analysis_by_radius$radius,analysis_by_radius$max_normalized,analysis_by_radius$radius, col="red", cex=.8)
	
	dev.off()
	
	
}