
#' based on CLUSTER FREQENCY PLOTTING SCRIPTv2.17 by Simon Maddison, 10th May 2015
#' This script extracts cluster frequency data and plots it for a range of percolation radii
#' The data is in the analysis_results-directory in text files created by the nodes_clust_freq-function;
#' 	each file is a list of Place indices, with the identity of each cluster
#' 	which it is a member of.
#' 	radius-values have been stored in the working_data-directory.
#' 	output will be put into /analysis_results
#' @author Simon Maddison
#' @author Sophie C. Schmidt
#' 
#' @import stats
#' @import calibrate
#' @import Hmisc
#' @import grDevices
#' @import graphics
#' @import utils
#' @param source_file_name needs input of source file name for plotting
#' @return plotClustFreq 3 plots of radius to maximum cluster size, radius to mean cluster size and radius to normalized max. cluster size
#' 
#' @export plotClustFreq
#'



# paths definition
plotClustFreq <- function(source_file_name) {
 
  path_working <- paste(getwd(),"/working_data",sep="")
  path_results <- paste(getwd(),"/analysis_results",sep="")

# load data generated by nodes_clust_freq-function
file_name <- paste(path_results,"/","analysis_by_radius.csv",sep="")
analysis_by_radius <- read.csv2(file_name,sep=",")

# Read in distance thresholds - this ensures same values used as in clustering script, where it was saved
file_name <- paste(path_working,"/","working_data.csv",sep="")
radius_values <- read.csv2(file_name,header=TRUE, sep = ",")
upper_radius <- radius_values$upper_radius
lower_radius <- radius_values$lower_radius
step_value <- radius_values$step_value
radius_unit <- radius_values$radius_unit
	
if (radius_unit == 1)
{unit_text <- "m"
} else if (radius_unit == 1000)
{unit_text <- "km"
} else {
  unit_text <- paste(radius_unit, "m", sep="")}	
	
	# output as png files

#removed if-condition  about percolation
	  output_file <- paste(path_results,"/cluster_plots_%02d.png",sep="")
	  plot_suffix <- ""
	
	png(file=output_file, units="cm", width=21, height=21, res=300)
	
	# Plot radius vs max_clust_size
	plot(analysis_by_radius$radius,analysis_by_radius$max_clust_size,
	     main=paste("Max cluster size vs radius ",plot_suffix),
	     sub=paste("Source File: ",source_file_name),
	     xlab=paste("radius ", unit_text),
	     ylab="max cluster size")
	lines(analysis_by_radius$radius,analysis_by_radius$max_clust_size, type="b")
#	textxy(analysis_by_radius$radius,analysis_by_radius$max_clust_size,analysis_by_radius$radius, col="red", cex=.8)
	# at the moment some weird mistake here: Error in if (sum(posXposY) > 0) text(X[posXposY], Y[posXposY], labs[posXposY],  : 
#	missing value where TRUE/FALSE needed
	# there shouldn't be any values missing.
	
	
	# Plot radius vs mean_clust_size
	plot(analysis_by_radius$radius,analysis_by_radius$mean_clust_size,
	     main=paste("Mean cluster size vs radius ",plot_suffix),
	     sub=paste("Source File: ",source_file_name),
	     xlab=paste("radius ", unit_text),
	     ylab="mean cluster size")
	lines(analysis_by_radius$radius,analysis_by_radius$mean_clust_size, type="b")
#	textxy(analysis_by_radius$radius,analysis_by_radius$mean_clust_size,analysis_by_radius$radius, col="red", cex=.8)
	
	# Plot radius vs normalized max_clust_size
	plot(analysis_by_radius$radius,analysis_by_radius$max_normalized,
	     main=paste("Max cluster size (normalized) vs radius ",plot_suffix),
	     sub=paste("Source File: ",source_file_name),
	     xlab=paste("radius ", unit_text),
	     ylab="max cluster size (normalized)")
	lines(analysis_by_radius$radius,analysis_by_radius$max_normalized, type="b")
#	textxy(analysis_by_radius$radius,analysis_by_radius$max_normalized,analysis_by_radius$radius, col="red", cex=.8)
	
	dev.off()
	
	
}